"""
This type stub file was generated by pyright.
"""

from .base import DataView

class DatabaseView(DataView):
    name = ...
    async def data(self, request, database, hash, default_labels=..., _size=...): # -> Response | tuple[dict[str, Unknown], () -> Coroutine[Any, Any, dict[str, Unknown]], list[str]] | tuple[dict[str, Unknown], () -> Coroutine[Any, Any, dict[str, Unknown]], list[str], Literal[400, 200]] | tuple[dict[str, Unknown], dict[str, Unknown], tuple[str, Literal['database.html']]]:
        ...
    


class DatabaseDownload(DataView):
    name = ...
    async def view_get(self, request, database, hash, correct_hash_present, **kwargs): # -> AsgiFileDownload:
        ...
    


class QueryView(DataView):
    async def data(self, request, database, hash, sql, editable=..., canned_query=..., metadata=..., _size=..., named_parameters=..., write=...): # -> Response | tuple[dict[str, Unknown], () -> Coroutine[Any, Any, dict[str, Unknown]], list[str]] | tuple[dict[str, Unknown], () -> Coroutine[Any, Any, dict[str, Unknown]], list[str], Literal[400, 200]]:
        ...
    


class MagicParameters(dict):
    def __init__(self, data, request, datasette) -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __getitem__(self, key): # -> None:
        ...
    


