"""
This type stub file was generated by pyright.
"""

from .base import BaseView

class JsonDataView(BaseView):
    name = ...
    def __init__(self, datasette, filename, data_callback, needs_request=...) -> None:
        ...
    
    async def get(self, request, as_format): # -> Response:
        ...
    


class PatternPortfolioView(BaseView):
    name = ...
    async def get(self, request): # -> Response:
        ...
    


class AuthTokenView(BaseView):
    name = ...
    async def get(self, request): # -> Response:
        ...
    


class LogoutView(BaseView):
    name = ...
    async def get(self, request): # -> Response:
        ...
    
    async def post(self, request): # -> Response:
        ...
    


class PermissionsDebugView(BaseView):
    name = ...
    async def get(self, request): # -> Response:
        ...
    


class AllowDebugView(BaseView):
    name = ...
    async def get(self, request): # -> Response:
        ...
    


class MessagesDebugView(BaseView):
    name = ...
    async def get(self, request): # -> Response:
        ...
    
    async def post(self, request): # -> Response:
        ...
    


