
title: Tasks Added & Removed (by workboard column)
db: metrics
requires: [ project, -column, -task_id ]
tab: hidden
order: 4
query: column_metrics_monthly
type: vega
display:
  height: 300
  autosize:
    type: fit
    contains: padding
  mark:
    type: bar
    tooltip:
      content: data
    baseline: bottom
    line: true
  encoding:
    size:
      value: 26
    # facet:
    #   columns: 3
    #   field: column_name
    #   type: ordinal
    #   title: Column
    #   spacing: 15
    #   margin: 5
    # color:
    #   field: column_name
    #   title: Tasks
    #   type: nominal
    x:
      field: month
      title: Month
      #type: temporal
      #timeUnit: monthyear
    xOffset:
      field: column_name
    y:
      field: total_tasks
      title: Task Count
      type: quantitative
      scale:
        scheme: blueorange
    tooltip:
      - field: action
        type: nominal
        title: Action
      - field: total_tasks
        type: quantitative
        title: Tasks
      - field: column_name
        type: nominal
        title: Workboard Column
      - field: month
        type: temporal
        title: Month
        timeUnit: monthyear
