"""
This type stub file was generated by pyright.
"""

def parsedate(value, dayfirst=..., yearfirst=...): # -> str:
    "Parse a date and convert it to ISO date format: yyyy-mm-dd"
    ...

def parsedatetime(value, dayfirst=..., yearfirst=...): # -> str:
    "Parse a datetime and convert it to ISO datetime format: yyyy-mm-ddTHH:MM:SS"
    ...

def jsonsplit(value, delimiter=..., type=...): # -> str:
    'Convert a string like a,b,c into a JSON array ["a", "b", "c"]'
    ...

