"""
This type stub file was generated by pyright.
"""

from datasette.version import __version__ as __version__
from datasette.version __version_info__ as __version_info__
from .hookspecs import hookimpl as hookimpl
from .hookspecs import hookspec as hookspec

