"""
This type stub file was generated by pyright.
"""

from datasette import hookimpl

def header(key, request): # -> str:
    ...

def actor(key, request):
    ...

def cookie(key, request):
    ...

def now(key, request): # -> int | str:
    ...

def random(key, request): # -> str:
    ...

@hookimpl
def register_magic_parameters(): # -> list[Unknown]:
    ...

