"""
This type stub file was generated by pyright.
"""

from datasette import hookimpl

@hookimpl(tryfirst=True)
def permission_allowed(datasette, actor, action, resource): # -> () -> Coroutine[Any, Any, bool | None]:
    ...

