"""
This type stub file was generated by pyright.
"""

HASH_BLOCK_SIZE = ...
def inspect_hash(path): # -> str:
    """Calculate the hash of a database, efficiently."""
    ...

def inspect_views(conn): # -> list[Unknown]:
    """List views in a database."""
    ...

def inspect_tables(conn, database_metadata): # -> dict[Unknown, Unknown]:
    """List tables and their row counts, excluding uninteresting tables."""
    ...

