"""
This type stub file was generated by pyright.
"""

def convert_specific_columns_to_json(rows, columns, json_cols): # -> list[Unknown]:
    ...

def json_renderer(args, data, view_name): # -> Response:
    """Render a response as JSON"""
    ...

