"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

tracers = ...
TRACE_RESERVED_KEYS = ...
def get_task_id(): # -> int | None:
    ...

@contextmanager
def trace(type, **kwargs): # -> Generator[None, None, None]:
    ...

@contextmanager
def capture_traces(tracer): # -> Generator[None, None, None]:
    ...

class AsgiTracer:
    max_body_bytes = ...
    def __init__(self, app) -> None:
        ...
    
    async def __call__(self, scope, receive, send): # -> None:
        ...
    


