"""
This type stub file was generated by pyright.
"""

class Urls:
    def __init__(self, ds) -> None:
        ...
    
    def path(self, path, format=...): # -> PrefixedUrlString:
        ...
    
    def instance(self, format=...): # -> PrefixedUrlString:
        ...
    
    def static(self, path): # -> PrefixedUrlString:
        ...
    
    def static_plugins(self, plugin, path): # -> PrefixedUrlString:
        ...
    
    def logout(self): # -> PrefixedUrlString:
        ...
    
    def database(self, database, format=...): # -> PrefixedUrlString:
        ...
    
    def table(self, database, table, format=...): # -> PrefixedUrlString:
        ...
    
    def query(self, database, query, format=...): # -> PrefixedUrlString:
        ...
    
    def row(self, database, table, row_path, format=...): # -> PrefixedUrlString:
        ...
    
    def row_blob(self, database, table, row_path, column): # -> PrefixedUrlString:
        ...
    


