"""
This type stub file was generated by pyright.
"""

"""
Backported from Python 3.8.

This code is licensed under the Python License:
https://github.com/python/cpython/blob/v3.8.3/LICENSE
"""
def copytree(src, dst, symlinks=..., ignore=..., copy_function=..., ignore_dangling_symlinks=..., dirs_exist_ok=...):
    ...

